### ISSUE TITLE
2.0.a.2 Doesn't work in Firefox 3.6

### ISSUE THREAD

**Issue by mrDarcyMurphy** [emberjs/starter-kit#2]
**Object.create is not a function**
3715: ret = m.mixins = Object.create(ret);

I haven't tried any other versions yet. According to the console Object only has _observes_, _observesBefore_, and _property_.
